### ISSUE TITLE
graphics acceleration and trackpad.

### ISSUE THREAD

**Issue by djtilapia** [DocSystem/razerbladehackintosh#3]
hi i reached out to you on youtube.

i have the Razer Blade mid-2019 i7 9750H with the RTX 2060.  i was able to install mojave on an SSD, (not the nvme), but unable to get graphics acceleration and trackpad to work.  i tried to follow your guide, but with no success.  i'm not sure if selecting different smbios makes a difference, or inject fake-id or ig-platform-id for the graphics would help either. or if i have to patch my own dsdt to get graphics working properly. i've tried.  i've tried using your efi without the patched dsdt files, and it ends with a panic. i've attached my efi folder if that helps.

thank you again for any help you can provide.
[EFI.zip](https://github.com/DocSystem/razerbladehackintosh/files/4270618/EFI.zip)

**Comment by psylou** [comment]
@djtilapia Please let us/me know when you got any updates according this issue. I got the same problem and tried so many things. I don't get the difference between our system and the system of @DocSystem

**Comment by DocSystem** [comment]
I don't understand why it doesn't work. Can you try with a clean Clover with [UHD 630 config by RehabMan](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/config_UHD630.plist) without patched DSDT and only Lilu and WhateverGreen kexts. You can try with this EFI folder :
[EFI.zip](https://github.com/DocSystem/razerbladehackintosh/files/4313962/EFI.zip)
You will only get Graphics working (not trackpad, battery, Wifi/Bluetooth, sound...)

**Comment by DocSystem** [comment]
And did you mod your BIOS? You need to change `DVMT Pre-Allocated` to `64MB` and `DVMT Total Gfx Mem` to `Max`

Here are all the changes you need to do : [Bios Configuration](https://github.com/stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#bios-configuration)
PS: You don't need to disable `Overclocking` because Base Model doesn't support it!

**Comment by DocSystem** [comment]
Also @djtilapia and @PTR-W can you run [RunMe.app](https://www.olarila.com/files/Utils/RunMe.app.zip) and send me your `Send Me*.zip` file

**Comment by psylou** [comment]
The EFI.zip you provided gives me a Blocked Sign about 1 second after the apple logo. (Did I maybe forget to put the .plist in there?)

 BIOS is and was modded as provided in the Guide, except changing XTU Interface in Overclock Settings, as there is no such tab in BIOS. Here is my 
[Send me Peters-MBP.zip](https://github.com/DocSystem/razerbladehackintosh/files/4318659/Send.me.Peters-MBP.zip)

Thank you for your help!

**Comment by DocSystem** [comment]
Hi @PTR-W
I just looked at your kextstat log and it seems like that not only the macOS base kexts and the one from EFI are loaded. AppleALC and AirPortBrcmFixup but they are not injected by Clover, if you installed them in `/Library/Extensions/` or `/System/Library/Extensions/` remove them from here and run `sudo kextcache -i /`

**Comment by DocSystem** [comment]
@PTR-W I recreated two Clover folders based on your EFI. One with some SSDT patches (but not DSDT, so no battery and no trackpad) and one without any patches. Can you try both and say me if one work! Thanks
[CLOVER-with-some-SSDT-patched.zip](https://github.com/DocSystem/razerbladehackintosh/files/4320422/CLOVER-with-some-SSDT-patched.zip)
[CLOVER-without-ACPI-patched.zip](https://github.com/DocSystem/razerbladehackintosh/files/4320419/CLOVER-without-ACPI-patched.zip)

**Comment by psylou** [comment]
I deleted all kexts and executed the command.

Sadly, both Clovers gave me the same reboot right after "gioscreenlockstate 3 hs 0 bs 0 now 0 sm 0x0". With both Clovers I was able to boot when changing platform-id to 0x12345678.

**Comment by djtilapia** [comment]
hi sorry for the delay. 

yes i modded the bios appropriately, and tried your suggestions, but none have worked.

i've attached the SendMe.zip
[Send me Fred-RAZER.zip](https://github.com/DocSystem/razerbladehackintosh/files/4346057/Send.me.Fred-RAZER.zip)

**Comment by DocSystem** [comment]
Hi!
Sorry for the delay...
I had some errors with macOS...
Sometimes I have the same error (gioscreenlockstate...) with my own Razer Blade. I didn’t solved them but I am able to boot macOS when I unplug the charger, wait for a few minutes, start macOS one time, wait for ACPIBatteryManagement... error, force reboot my computer and then restart macOS, and it worked!
I will look at your Send Me file later, @djtilapia
Sorry for the late
DocSystem

**Comment by DocSystem** [comment]
Hi!
@djtilapia can you upgrade your CLOVER to the latest version! It can fix some errors! In addition, your Clover version supports up to macOS 10.13 High Sierra, so it will not work in Mojave!
In your ``kexts`` folder, you have ``AtherosE2200Ethernet.kext`` and ``IntelMausiEthernet.kext``. But the Razer Blade has a Realtek network card. So you don't need to use Atheros and Intel kexts!
I don't know if you upgraded your wifi card but if not, the ``AirportBrcmFixup.kext``, ``BrcmFirmwareRepo.kext`` and ``BrcmPatchRAM2.kext`` won't be needed. So please remove all them!
In your config.plist files you have a lot of things that aren't useful:
* In your boot arguments, please remove ``darkwake=8`` and ``kext-dev-mode=1``, they are useless.
* Don't Inject Intel in Graphics > Inject. It isn't needed with Intel UHD Graphics 630!

**Comment by DocSystem** [comment]
I added some changes to the guide. It can help you to get your Hackintosh working @djtilapia @PTR-W !!!
[https://github.com/DocSystem/razerbladehackintosh/commit/134a4d809e33a9e897816d1318130a5f2c82b973](https://github.com/DocSystem/razerbladehackintosh/commit/134a4d809e33a9e897816d1318130a5f2c82b973)

**Comment by PTR-W** [comment]
So let's say I want to start from scratch. What should I do?

**Comment by psylou** [comment]
Ok. So I added VirtualSMC and SMCBatteryManager but now I'm stuck at "previous shutdown cause 5".  I'm not really sure what could possibly be different from your setup.

Edit: Ok, had to remove FakeSMC in order to get further. now I'm back at giolockstate...

Just the facts if you got any other idea:

stock Intel Wifi Card,
2nd SSD 2.5 "Sandisk PLUS 2 TB"

I'm out of ideas.

![20200419_194355](https://user-images.githubusercontent.com/8116196/79695325-8063d700-8276-11ea-8f3a-a80a92036180.jpg)

**Comment by djtilapia** [comment]
@PTR-W @DocSystem honestly, i've chalked this up to a loss for the time being. seems the only EFI folder i can get working is my own.  i'm able to boot into Mojave, but it doesn't have graphics acceleration or trackpad working.  i've tried other people's EFI folders, and config.plist files but none work. either they hang, or it just reboots the system, and in some cases i get an error saying something like, "Mac OS is supported by this platform." i've tried almost everyone's suggestions, with no success or it breaks something.  i've correctly modded the bios, and followed step by step guides.  which is weird, because other than some hardware differences, like the nvme or wifi card, we pretty much have the same system.  but i do appreciate everyone's assistance, it's a lot of work. i'll just keep holding my breath until something works for my particular system (it seems).

**Comment by djtilapia** [comment]
@PTR-W hey, i just wanted to share you my EFI folder, and maybe it'll work with you.  I was able to get graphics acceleration working with a config.plist file i found on another forum, and it worked for me.  i'm still unable to get the trackpad working, i followed the guide that was posted on this github but still didn't work. i'm running Mojave 10.14.6
[EFI.zip](https://github.com/DocSystem/razerbladehackintosh/files/4565973/EFI.zip)

**Comment by psylou** [comment]
@djtilapia Holy cow! It actually worked. The razer is running pretty hot while doing nothing, but it works!

**Comment by djtilapia** [comment]
@PTR-W yeah, the fans seem to run a little loud. i'll have to do more research. along with how to get the trackpad to work, but baby steps i guess. it's a lot of reading and scouring the internet for working solutions. but seems you and me have identical systems, so if you solve anything, please share, i'll do the same. thanks.

**Comment by DocSystem** [comment]
Do you want I add you to collaborators so you can modify the guide with the working things?

**Comment by DocSystem** [comment]
Oh! I just seen I forgot an important thing in the trackpad part in the guide! I will fix it tomorrow but I forgot something of important in the config.plist file!

**Comment by psylou** [comment]
@djtilapia Of course I'll do the same! Thanks for sharing what you accomplished. Any change to find out, what tutorial you followed, because the EFI folder is like completely packed of things. I'm sure the first thing would be making it as light as @DocSystem EFI Folder. And we'll be able to isolate, what was different from his system.

**Comment by psylou** [comment]
[EFI.zip](https://github.com/blade15basehackintosh/razerbladehackintosh/files/4569036/EFI.zip)

So what happened for me so far:

- If I press Enter for too long when selecting MacOS I'm getting kernel panic (blocked sign)
- I managed to patch DSDT to get Battery percentage with given tutorial from @DocSystem  
- I deleted all the folders that not seem to have any effect on EFI. 
- I deleted all the kexts like lilufriend and Atheros Ethernet that are not needed for our setup I guess (I uploaded my current EFI @djtilapia)

What is still needed:

- @DocSystem How did you manage to use VirtualSMC as battery manager? 
- What exactly is missing for getting trackpad support?

**Comment by DocSystem** [comment]
Hi!
At first, I want to say that I never said that you need to install Atheros Ethernet kext because the Blade has a Realtek Ethernet card!
For the Virtual SMC battery support, I will explain it later because for the moment the ACPI method works!
For the trackpad support, see this commit: https://github.com/blade15basehackintosh/razerbladehackintosh/commit/46eb22d8465ad0d647ce345236551be1d771217c. I added what is needed to get trackpad working!

**Comment by DocSystem** [comment]
@PTR-W your EFI folder is good but you can remove the ``IntelMausiEthernet`` kext because the Razer Blade has a Realtek Ethernet card so you only need the ``RealtekRTL8111`` kext

**Comment by DocSystem** [comment]
The problem is solved so I close the issue

**Comment by DocSystem** [comment]
@PTR-W Just a question, after looking at your config.plist file, and using a little soft to find the changes between both, I saw that you were using layout-id 30 for audio, and you named it ALC298, were you able to get audio working? If yes, can you send me a screenshot of the ``System`` > ``Peripherals`` page of [Hackintool](https://github.com/headkaze/Hackintool/releases). It should look like this:
![image](https://user-images.githubusercontent.com/42613513/81397295-4b38ff00-9127-11ea-96ef-e30654c14c4d.png)

Thanks!

**Comment by psylou** [comment]
@DocSystem I had to change back to layout-id 13. Not working otherwise.
By the way, trackpad is still not working for me. @djtilapia did you manage to get it working?

**Comment by djtilapia** [comment]
@PTR-W @DocSystem no i was unable to get the trackpad to work with the additional instructions.  i followed the updated guide, but when i boot, it just hangs.
